# Generated by Django 4.1.2 on 2024-02-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "DEPOSIT"),
                            ("WITHDRAWAL", "WITHDRAWAL"),
                            ("FUNDS_LOCKED_BUYER", "FUNDS_LOCKED_BUYER"),
                            ("FUDNS_LOCKED_SELLER", "FUDNS_LOCKED_SELLER"),
                            ("FUNDS_UNLOCKED_BUYER", "FUNDS_UNLOCKED_BUYER"),
                            ("FUDNS_UNLOCKED_SELLER", "FUDNS_UNLOCKED_SELLER"),
                            ("DISPUTE_RAISED_AUTHOR", "DISPUTE_RAISED_AUTHOR"),
                            ("DISPUTE_RAISED_RECIPIENT", "DISPUTE_RAISED_RECIPIENT"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("content", models.TextField()),
                ("is_seen", models.BooleanField(default=False)),
                ("action_url", models.URLField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("is_seen", "-created_at"),
            },
        ),
    ]
