# Generated by Django 4.1.2 on 2024-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_usernotification_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "DEPOSIT"),
                    ("WITHDRAWAL", "WITHDRAWAL"),
                    ("ESCROW_APPROVED", "ESCROW_APPROVED"),
                    ("ESCROW_REJECTED", "ESCROW_REJECTED"),
                    ("FUNDS_LOCKED_BUYER", "FUNDS_LOCKED_BUYER"),
                    ("FUNDS_LOCKED_SELLER", "FUNDS_LOCKED_SELLER"),
                    ("FUNDS_UNLOCKED_BUYER", "FUNDS_UNLOCKED_BUYER"),
                    ("FUNDS_UNLOCKED_SELLER", "FUNDS_UNLOCKED_SELLER"),
                    ("DISPUTE_RAISED_AUTHOR", "DISPUTE_RAISED_AUTHOR"),
                    ("DISPUTE_RAISED_RECIPIENT", "DISPUTE_RAISED_RECIPIENT"),
                    ("DISPUTE_RESOLVED", "DISPUTE_RESOLVED"),
                ],
                max_length=255,
            ),
        ),
    ]
