version: "3.8"

services:
  api: &api
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
    volumes:
      - ./src:/app
      - myb-dev-static-data:/vol/web
    # ports:
    #   - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - myb
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8000"
    depends_on:
      - api
    networks:
      - myb

  db:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - myb-dev-db:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - myb

  redis:
    image: redis:alpine
    networks:
      - myb

  celery:
    <<: *api
    command: >
      sh -c "celery -A core worker -l INFO --logfile=celery.log"
    ports: []
    volumes:
      - ./src:/app
    env_file:
      - ./.env
    depends_on:
      - api
    networks:
      - myb

volumes:
  myb-dev-static-data:
  myb-dev-db:
networks:
    myb:
      driver: bridge
