# Generated by Django 5.1.2 on 2024-10-31 17:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image_url',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvw89fvtm/image/upload/v1730395134/greenhouse/w4s8sbtkddkf9ulwfklh.svg', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
