# Generated by Django 5.1.2 on 2024-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_cover_image_url_blogpost_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
    ]
