# Generated by Django 4.1.2 on 2024-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_tag_blogpost_published_at_alter_blogpost_is_draft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
