# Generated by Django 4.1.2 on 2024-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="escrow_redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchant",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
