# Generated by Django 4.1.2 on 2024-04-07 00:26

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_merchant_escrow_redirect_url_merchant_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="api_key",
            field=models.CharField(default=utils.utils.get_priv_key, max_length=255),
        ),
    ]
