# Generated by Django 4.1.2 on 2024-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0005_alter_customermerchant_alternate_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermerchant",
            name="alternate_email",
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customermerchant",
            name="user_type",
            field=models.CharField(
                choices=[("BUYER", "BUYER"), ("SELLER", "SELLER")],
                default="BUYER",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
