# Generated by Django 4.1.2 on 2024-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0006_customermerchant_alternate_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermerchant",
            name="alternate_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
