# Generated by Django 4.1.2 on 2024-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0007_customermerchant_alternate_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermerchant",
            name="name_match",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customermerchant",
            name="phone_number_match",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customermerchant",
            name="user_type_match",
            field=models.BooleanField(default=True),
        ),
    ]
