# Generated by Django 4.1.2 on 2024-04-25 02:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0008_customermerchant_name_match_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="escrow_redirect_url",
        ),
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "buyer_redirect_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "seller_redirect_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "webhook_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchant",
                    ),
                ),
            ],
        ),
    ]
