# Generated by Django 4.1.2 on 2024-04-29 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0010_remove_merchant_api_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "buyer_payment_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FLAT_FEE", "Flat Fee"),
                            ("NO_FEES", "No Fees"),
                        ],
                        default="NO_FEES",
                        max_length=255,
                    ),
                ),
                (
                    "buyer_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "seller_payment_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FLAT_FEE", "Flat Fee"),
                            ("NO_FEES", "No Fees"),
                        ],
                        default="NO_FEES",
                        max_length=255,
                    ),
                ),
                (
                    "seller_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchant.merchant",
                    ),
                ),
            ],
        ),
    ]
