# Generated by Django 4.1.2 on 2024-04-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0011_payoutconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutconfig",
            name="name",
            field=models.CharField(default="ERP", max_length=255),
            preserve_default=False,
        ),
    ]
