# Generated by Django 4.1.2 on 2024-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0012_payoutconfig_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payoutconfig",
            old_name="buyer_payment_type",
            new_name="buyer_charge_type",
        ),
        migrations.RenameField(
            model_name="payoutconfig",
            old_name="seller_payment_type",
            new_name="seller_charge_type",
        ),
        migrations.AlterField(
            model_name="payoutconfig",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
