# Generated by Django 4.1.2 on 2024-04-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "merchant",
            "0013_rename_buyer_payment_type_payoutconfig_buyer_charge_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="enable_payout_splitting",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="payout_splitting_ratio",
        ),
    ]
