# Generated by Django 4.1.2 on 2024-06-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0014_remove_merchant_enable_payout_splitting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermerchant",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("BUYER", "BUYER"),
                    ("SELLER", "SELLER"),
                    ("CUSTOM", "CUSTOM"),
                ],
                max_length=255,
            ),
        ),
    ]
