# Generated by Django 4.1.2 on 2024-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0015_alter_customermerchant_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payoutconfig",
            name="buyer_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payoutconfig",
            name="seller_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
