# Generated by Django 4.1.2 on 2023-05-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_bankaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NIN", "NATIONAL_IDENTIFICATION_NUMBER"),
                            ("BVN", "BANK_VERIFICATION_NUMBER"),
                            ("DL", "DRIVER_LICENSE"),
                            ("VC", "VOTER_CARD"),
                            ("IP", "INTERNATIONAL_PASSPORT"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        default="INACTIVE",
                        max_length=255,
                    ),
                ),
                ("nin", models.CharField(blank=True, max_length=11, null=True)),
                ("bvn", models.CharField(blank=True, max_length=11, null=True)),
                ("dl_metadata", models.JSONField(blank=True, null=True)),
                ("vc_metadata", models.JSONField(blank=True, null=True)),
                ("inp_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
