# Generated by Django 4.1.2 on 2023-05-04 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        ("users", "0003_userkyc"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("avatar", models.URLField(blank=True, null=True)),
                ("profile_link", models.URLField(blank=True, null=True)),
                (
                    "wallet_balance",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "locked_amount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "unlocked_amount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="business.business",
                    ),
                ),
                (
                    "kyc_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.userkyc",
                    ),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
