# Generated by Django 4.1.2 on 2023-05-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_login_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
