# Generated by Django 4.1.2 on 2023-05-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_last_login_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="bank_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
