# Generated by Django 4.1.2 on 2023-05-07 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_bankaccount_bank_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bank_account_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.bankaccount",
            ),
        ),
    ]
