# Generated by Django 4.1.2 on 2023-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_bank_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("BUYER", "BUYER"),
                    ("SELLER", "SELLER"),
                    ("CONTRACTOR", "CONTRACTOR"),
                ],
                default="BUYER",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
