# Generated by Django 4.1.2 on 2023-08-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_bankaccount_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="withdrawn_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
