# Generated by Django 4.1.2 on 2023-10-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userprofile_withdrawn_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="free_escrow_transactions",
            field=models.IntegerField(default=2),
        ),
    ]
