# Generated by Django 4.1.2 on 2023-10-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userprofile_free_escrow_transactions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userkyc",
            name="bvn",
        ),
        migrations.RemoveField(
            model_name="userkyc",
            name="nin",
        ),
        migrations.AddField(
            model_name="userkyc",
            name="bvn_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userkyc",
            name="nin_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
