# Generated by Django 4.1.2 on 2023-11-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_userkyc_bvn_remove_userkyc_nin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="free_escrow_transactions",
            field=models.IntegerField(default=5),
        ),
    ]
