# Generated by Django 4.1.2 on 2024-01-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_userprofile_free_escrow_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="show_tour_guide",
            field=models.BooleanField(default=True),
        ),
    ]
