# Generated by Django 4.1.2 on 2024-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_userprofile_show_tour_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
