# Generated by Django 4.1.2 on 2024-03-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
