# Generated by Django 4.1.2 on 2024-06-23 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="uuid_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE public.users_wallet SET uuid_id = gen_random_uuid() WHERE uuid_id IS NULL;
                ALTER TABLE public.users_wallet DROP CONSTRAINT users_wallet_pkey;
                ALTER TABLE public.users_wallet ADD PRIMARY KEY (uuid_id);
                ALTER TABLE public.users_wallet DROP COLUMN id;
                ALTER TABLE public.users_wallet RENAME COLUMN uuid_id TO id;
            """,
            reverse_sql="""
                -- Optional reverse migration steps, if needed
            """,
        ),
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        # migrations.RemoveField(
        #     model_name="wallet",
        #     name="uuid_id",
        # ),
    ]
