# Generated by Django 4.1.2 on 2024-06-23 13:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wallet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
