# Generated by Django 4.1.2 on 2024-06-23 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_remove_wallet_uuid_id_wallet_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="locked_amount_inward",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="wallet",
            name="locked_amount_outward",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="wallet",
            name="unlocked_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="wallet",
            name="withdrawn_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
