# Generated by Django 4.1.2 on 2024-06-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_remove_wallet_uuid_id_wallet_locked_amount_inward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
