# Generated by Django 4.1.2 on 2024-06-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_wallet_uuid_id_wallet_flagged_alter_wallet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("BUYER", "BUYER"),
                    ("SELLER", "SELLER"),
                    ("MERCHANT", "MERCHANT"),
                    ("CUSTOM", "CUSTOM"),
                ],
                max_length=255,
            ),
        ),
    ]
