# Generated by Django 4.1.2 on 2024-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="referrer",
            field=models.CharField(default="NEUTRAL", max_length=255),
        ),
    ]
