# Generated by Django 4.1.2 on 2024-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_remove_wallet_uuid_id_userprofile_referrer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="referrer",
            field=models.CharField(default="OTHERS", max_length=255),
        ),
    ]
