# Generated by Django 4.1.2 on 2024-08-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_alter_userprofile_referrer"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="deactivated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="flagged_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_deactivated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
