# Generated by Django 4.1.2 on 2024-08-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_remove_wallet_uuid_id_userprofile_deactivated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
