# Generated by Django 4.1.2 on 2025-01-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_alter_customuser_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="uuid_id",
        ),
    ]
