# Generated by Django 5.1.2 on 2024-10-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='uuid_id',
        ),
    ]
