# Generated by Django 4.1.2 on 2025-01-21 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0016_alter_payoutconfig_buyer_amount_and_more"),
        ("users", "0030_remove_wallet_uuid_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.merchant",
            ),
        ),
    ]
