# Generated by Django 4.1.2 on 2025-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_wallet_merchant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankaccount",
            name="is_active",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
