# Generated by Django 4.1.2 on 2023-06-12 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESSFUL", "SUCCESSFUL"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEPOSIT", "DEPOSIT"), ("WITHDRAW", "WITHDRAW")],
                        max_length=255,
                    ),
                ),
                ("mode", models.CharField(max_length=255)),
                ("reference", models.CharField(max_length=255)),
                ("narration", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.IntegerField(blank=True, default=0, null=True)),
                ("charge", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "remitted_amount",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("currency", models.CharField(default="NGN", max_length=255)),
                ("provider", models.CharField(max_length=255)),
                (
                    "provider_tx_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
