# Generated by Django 4.1.2 on 2023-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0002_alter_transaction_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                max_length=255,
            ),
        ),
    ]
