# Generated by Django 4.1.2 on 2023-07-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("console", "0003_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FLUTTERWAVE", "FLUTTERWAVE"),
                    ("PAYSTACK", "PAYSTACK"),
                    ("BLUSALT", "BLUSALT"),
                    ("MYBALANCE", "MYBALANCE"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                    ("PAUSED", "PAUSED"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "DEPOSIT"),
                    ("WITHDRAW", "WITHDRAW"),
                    ("ESCROW", "ESCROW"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="EscrowMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        choices=[("BUYER", "BUYER"), ("SELLER", "SELLER")],
                        max_length=255,
                    ),
                ),
                ("purpose", models.TextField()),
                ("item_type", models.CharField(max_length=255)),
                ("item_quantity", models.IntegerField()),
                ("delivery_date", models.DateField()),
                (
                    "delivery_tolerance",
                    models.IntegerField(blank=True, default=3, null=True),
                ),
                ("charge", models.IntegerField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_escrow_meta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_escrow_meta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transation_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="console.transaction",
                    ),
                ),
            ],
        ),
    ]
