# Generated by Django 4.1.2 on 2023-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "console",
            "0004_alter_transaction_provider_alter_transaction_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                    ("PAUSED", "PAUSED"),
                    ("FUFILLED", "FUFILLED"),
                ],
                max_length=255,
            ),
        ),
    ]
