# Generated by Django 4.1.2 on 2023-08-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0005_alter_transaction_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escrowmeta",
            name="buyer_id",
        ),
        migrations.RemoveField(
            model_name="escrowmeta",
            name="seller_id",
        ),
        migrations.AddField(
            model_name="escrowmeta",
            name="partner_email",
            field=models.EmailField(default="superadmin@email.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                    ("PAUSED", "PAUSED"),
                    ("FUFILLED", "FUFILLED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                ],
                max_length=255,
            ),
        ),
    ]
