# Generated by Django 4.1.2 on 2023-08-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0006_remove_escrowmeta_buyer_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="escrowmeta",
            old_name="transation_id",
            new_name="transaction_id",
        ),
    ]
