# Generated by Django 4.1.2 on 2023-08-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("console", "0007_rename_transation_id_escrowmeta_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="LockedAmount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ESCROW", "ESCROW"),
                            ("SETTLED", "SETTLED"),
                            ("DISPUTE_RAISED", "DISPUTE_RAISED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locked_amounts_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="console.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locked_amounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
