# Generated by Django 4.1.2 on 2023-08-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0008_alter_transaction_reference_lockedamount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lockedamount",
            name="seller",
        ),
        migrations.AddField(
            model_name="lockedamount",
            name="seller_email",
            field=models.EmailField(
                default="tosxnthdesigner@gmail.com", max_length=254
            ),
            preserve_default=False,
        ),
    ]
