# Generated by Django 4.1.2 on 2023-08-28 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0011_dispute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispute",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="console.transaction"
            ),
        ),
    ]
