# Generated by Django 4.1.2 on 2023-10-04 16:47

import console.models.identity
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0012_alter_dispute_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="NINIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=11,
                        validators=[console.models.identity.validate_number],
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ZEEHAFRICA", "ZEEHAFRICA"),
                            ("VERIFYME", "VERIFYME"),
                        ],
                        max_length=255,
                    ),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
