# Generated by Django 4.1.2 on 2023-10-04 17:42

import console.models.identity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0013_ninidentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ninidentity",
            name="number",
            field=models.CharField(
                db_index=True,
                max_length=11,
                unique=True,
                validators=[console.models.identity.validate_number],
            ),
        ),
    ]
