# Generated by Django 4.1.2 on 2023-10-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0014_alter_ninidentity_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ninidentity",
            name="provider",
            field=models.CharField(
                choices=[
                    ("ZEEHAFRICA", "ZEEHAFRICA"),
                    ("VERIFYME", "VERIFYME"),
                    ("MYBALANCE", "MYBALANCE"),
                ],
                max_length=255,
            ),
        ),
    ]
