# Generated by Django 4.1.2 on 2024-04-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0003_alter_merchant_api_key"),
        ("console", "0015_alter_ninidentity_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="escrowmeta",
            name="author",
            field=models.CharField(
                choices=[
                    ("BUYER", "BUYER"),
                    ("SELLER", "SELLER"),
                    ("MERCHANT", "MERCHANT"),
                ],
                max_length=255,
            ),
        ),
    ]
