# Generated by Django 4.1.2 on 2024-04-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0016_transaction_merchant_alter_escrowmeta_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="source",
            field=models.CharField(
                choices=[("PLATFORM", "PLATFORM"), ("API", "API")],
                default="PLATFORM",
                max_length=255,
            ),
        ),
    ]
