# Generated by Django 4.1.2 on 2024-04-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0011_payoutconfig"),
        ("console", "0017_dispute_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowmeta",
            name="payout_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.payoutconfig",
            ),
        ),
    ]
