# Generated by Django 4.1.2 on 2024-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0018_escrowmeta_payout_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "DEPOSIT"),
                    ("WITHDRAW", "WITHDRAW"),
                    ("ESCROW", "ESCROW"),
                    ("MERCHANT_SETTLEMENT", "MERCHANT_SETTLEMENT"),
                ],
                max_length=255,
            ),
        ),
    ]
