# Generated by Django 4.1.2 on 2024-05-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0019_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowmeta",
            name="parent_payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_payment_transaction",
                to="console.transaction",
            ),
        ),
    ]
