# Generated by Django 4.1.2 on 2024-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0020_escrowmeta_parent_payment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "NGN"), ("USD", "USD")], default="NGN", max_length=255
            ),
        ),
    ]
