# Generated by Django 4.1.2 on 2024-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0022_alter_transaction_status_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowmeta",
            name="buyer_consent_to_unlock",
            field=models.BooleanField(default=False),
        ),
    ]
