# Generated by Django 4.1.2 on 2024-07-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0023_escrowmeta_buyer_consent_to_unlock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                    ("PAUSED", "PAUSED"),
                    ("FUFILLED", "FUFILLED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("REVOKED", "REVOKED"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
