# Generated by Django 4.1.2 on 2024-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0024_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "NGN"), ("USD", "USD")],
                db_index=True,
                default="NGN",
                max_length=255,
            ),
        ),
    ]
