# Generated by Django 4.1.2 on 2024-08-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0025_alter_transaction_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("FLUTTERWAVE", "FLUTTERWAVE"),
                    ("PAYSTACK", "PAYSTACK"),
                    ("BLUSALT", "BLUSALT"),
                    ("STRIPE", "STRIPE"),
                    ("MYBALANCE", "MYBALANCE"),
                ],
                max_length=255,
            ),
        ),
    ]
