# Generated by Django 4.1.2 on 2024-08-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "console",
            "0031_event_product_alter_transaction_type_ticketpurchase_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
