# Generated by Django 4.1.2 on 2024-08-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0032_product_slug_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
