# Generated by Django 4.1.2 on 2024-08-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0033_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="provider_mode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
