# Generated by Django 4.1.2 on 2024-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0034_transaction_provider_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "DEPOSIT"),
                    ("WITHDRAW", "WITHDRAW"),
                    ("ESCROW", "ESCROW"),
                    ("MERCHANT_SETTLEMENT", "MERCHANT_SETTLEMENT"),
                    ("PRODUCT", "PRODUCT"),
                    ("SETTLEMENT", "SETTLEMENT"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
