# Generated by Django 4.1.2 on 2024-10-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0035_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("SUCCESSFUL", "SUCCESSFUL"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                    ("PAUSED", "PAUSED"),
                    ("FUFILLED", "FUFILLED"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("REVOKED", "REVOKED"),
                    ("EXPIRED", "EXPIRED"),
                ],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
