# Generated by Django 4.1.2 on 2024-12-11 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0016_alter_payoutconfig_buyer_amount_and_more"),
        ("console", "0036_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="merchant.merchant",
            ),
        ),
    ]
